version: '3'

services:
  web:
   image: richard/docker_swarm_node
   ports:
     - 3000:3000
   deploy:
     replicas: 3
     restart_policy:
       max_attempts: 3
       condition: on-failure       
     update_config:
       parallelism: 3
       delay: 5s
   networks: 
    - balance 
  
  proxy:
    image: richard/docker_swarm_nginx
    ports:
      - 80:80
    depends_on:
      - web
    deploy:
      placement:
        constraints: [node.role == manager]
    networks: 
      - balance

networks:
  balance:
    driver: overlay
